services:
  database:
    image: mysql
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: redis
    ports:
      - "3306:3306"
  cache:
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    ports:
      - "6379:6379"